import '@/styles/globals.css';

export const metadata = {
  title: 'Next.js 13 | Starter',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
